---
apiVersion: v1
kind: Service
metadata:
  name: ren
  labels:
    app: ren
spec:
  type: ClusterIP
  selector:
    app: ren
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
