project_name: kustomize-plgins
dist: dist

gomod:
  proxy: true

builds:
  - id: vars-transformer
    main: ./cmd/vars-transformer
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: vars-transformer
    builds:
      - vars-transformer
    name_template: 'vars-transformer_{{ .Os }}_{{ .Arch }}'
    format: binary

release:
  prerelease: auto

changelog:
  skip: true

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"