---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ren

resources:
  - ../../base

transformers:
  - |-
    apiVersion: wiersma.io/v1alpha1
    kind: VarsTransformer
    metadata:
      name: config
      annotations:
        config.kubernetes.io/function: |-
          exec:
            path: vars-transformer
    replacements:
      - name: NAMESPACE
        source:
          objRef: {apiVersion: apps/v1, kind: Deployment, name: ren}
          fieldPath: metadata.namespace
